
[other]

	[other.avoid_attributes_low-level_and_high-level_composition]
		avoid_attributes_low-level_and_high-level_composition = true
		attributes_protect = false

	[other.health_warn]
		health_lower_than_how_much_percent_warn_ = 50
		health_warn = false

	[other.frag_bot]
		frag_bot = false

	[other.ice_spray]
		ice_spray_range = false

	[other.flare_time]
		flare_timer_ = false

	[other.attributes]
		attribute_search = ""

	[other.item_search]
		"item_search(enchanted/attribute)" = true

	[other.precise]
		precise_pos_display = false

	[other.current_time]
		current_time = false

	[other.flare_range_marker]
		"flare/power_orb_range_marker" = 0

[dungeon]

	[dungeon.star_mob_mark]
		mark_star_mob = false

	[dungeon.dungeon_pet_check]
		dungeon_pet_check = false

	[dungeon.fire_freeze]
		fire_freeze = false

	[dungeon.low_hp_warn]
		when_the_hp_is_lower_than_how_much_warning = 5000
		low_hp_warn = false

	[dungeon.mimic]
		mimic_killed = true
		mimic_killed_message = ""

	[dungeon.ndt]
		ndt = false
		"dt_time_(s)" = 1

[party]

	[party.always_party_all_invite]
		allow_party_member_setting_allinvite = false

	[party.allow_party_someone]
		allow_party_member_party_someone = false

	[party.auto_transfer_party]
		"auto_transfer_party(testing)" = false

